{% set name = "ncdu" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://dev.yorhel.nl/download/{{ name }}-{{ version }}.tar.gz
  sha256: 4ba8d20a64a55cc00af2d2c6138afcc9dc25e40a5ed6a8c544cb9e2285a195fe
  patches:
    - 0001-Hard-code-constants-that-are-not-present-in-CentOS-6.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
    - pkg-config
  host:
    - ncurses
  run:
    - ncurses

test:
  commands:
    - ncdu --version

about:
  home: https://dev.yorhel.nl/ncdu
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: NCurses Disk Usage
  description: |
    Ncdu is a disk usage analyzer with an ncurses interface. It is designed to
    find space hogs on a remote server where you don't have an entire graphical
    setup available, but it is a useful tool even on regular desktop systems.
    Ncdu aims to be fast, simple and easy to use, and should be able to run
    in any minimal POSIX-like environment with ncurses installed.
  doc_url: https://dev.yorhel.nl/ncdu/man
  dev_url: https://g.blicky.net/ncdu.git/

extra:
  recipe-maintainers:
    - chrisburr
