schema_version: 1

context:
  name: ncdu
  version: "2.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://dev.yorhel.nl/download/${{ name }}-${{ version }}.tar.gz
  sha256: 75f0ac3bce4fc012e8198b72518db5179e903079858efce08b912d5dcc7094d3

build:
  number: 0
  skip: win or ppc64le

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - zig 0.14.*
    - pkg-config
  host:
    - ncurses
    - zstd
  run:
    - ncurses
    - zstd

tests:
  - script:
      - ncdu --version

about:
  license: MIT
  license_file: LICENSES/MIT.txt
  summary: NCurses Disk Usage
  description: |
    Ncdu is a disk usage analyzer with an ncurses interface. It is designed to
    find space hogs on a remote server where you don't have an entire graphical
    setup available, but it is a useful tool even on regular desktop systems.
    Ncdu aims to be fast, simple and easy to use, and should be able to run
    in any minimal POSIX-like environment with ncurses installed.
  homepage: https://dev.yorhel.nl/ncdu
  repository: https://g.blicky.net/ncdu.git/
  documentation: https://dev.yorhel.nl/ncdu/man

extra:
  recipe-maintainers:
    - chrisburr
    - carlodri
